WAIT_BETWEEN_ACCOUNTS = [0, 0]
MAX_TRIES = 2

# Only one of this needed
TWO_CAPTCHA_API_KEY = ""
CAP_SOLVER_API_KEY = ""

THREADS_NUM = 1
DISABLE_SSL = false

CHECKER_UPDATE_STORAGE = false

UPDATE_STORAGE_ACCOUNT_INFO = true
SKIP_FIRST_ACCOUNTS = 0
RANDOM_ORDER = false

FAKE_TWITTER = false
FORCE_LINK_EMAIL = false

GALXE_CAMPAIGN_IDS = ["GCTN3ttM4T", "GC433ttn6N"]
HIDE_UNSUPPORTED = false

# Spaces aliases to track all points. If empty returns all used spaces
SPACES_STATS = []

[RPCs]
Ethereum = 'https://rpc.ankr.com/eth'
Optimism = 'https://mainnet.optimism.io'
BSC = 'https://rpc.ankr.com/bsc'
Polygon = 'https://polygon-bor.publicnode.com'
Arbitrum = 'https://arb1.arbitrum.io/rpc'
Avalanche = 'https://avalanche-c-chain.publicnode.com'
Base = 'https://mainnet.base.org'
Scroll = 'https://1rpc.io/scroll'
