WAIT_BETWEEN_ACCOUNTS = [0, 0]
MAX_TRIES = 2

THREADS_NUM = 1
DISABLE_SSL = false

CHECKER_UPDATE_STORAGE = false

UPDATE_STORAGE_ACCOUNT_INFO = true
SKIP_FIRST_ACCOUNTS = 0
RANDOM_ORDER = false

FAKE_TWITTER = true
FORCE_LINK_EMAIL = false

GALXE_CAMPAIGN_IDS = ["GCTN3ttM4T", "GC433ttn6N"]
HIDE_UNSUPPORTED = false
